### ISSUE TITLE
The master branch will be renamed to main

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/github-actions#14]
In line with our new org-wide policy, the `master` branch of this repo will be renamed to `main`. All open PRs will be automatically repointed.

GitHub will show you a notification about this when you look at this repo after renaming:

<img width="534" alt="Screenshot 2021-01-27 at 15 31 45" src="https://user-images.githubusercontent.com/286476/106013980-e9556680-60b4-11eb-992c-606b9f84a0b5.png">

In case it doesn't, this is the command it suggests:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

You may like to update the primary branch on your forks too, which you can do under Settings->Branches and clicking the pencil icon on the right-hand-side under Default Branch:

<img width="933" alt="Screenshot 2021-01-27 at 18 50 08" src="https://user-images.githubusercontent.com/286476/106039011-84a80500-60d0-11eb-87d2-8c3ab3524523.png">

We will post a comment below when this is done. We expect it to happen within the next 12 hours.

**Comment by SaschaMann** [comment]
Will the workflows calling these actions also be updated?

**Comment by ee7** [comment]
> Will the workflows calling these actions also be updated?

I had the same question.

I looked at the `v3-migration` branches on Erik's forks and I think the current state is as follows.

---

For tracks that lack a `.github/workflows/configlet.yml` file: there is a commit that adds that file, which contains 
```
uses: exercism/github-actions/configlet-ci@main
```

Example: 
https://github.com/ErikSchierboom/python/commit/62d5b7abd52a6fa5a7ca01406f381b56fa02d1de#diff-2041228d170e6a304159c590fa51bd13824a6b6058e9cc6f2babb9ba132b2396R13

---

For tracks that have a `.github/workflows/configlet.yml` file: the branch doesn't touch the file - it will still contain
```
uses: exercism/github-actions/configlet-ci@master
```

Example: https://github.com/ErikSchierboom/julia/blob/8d9f3c8ba06e10633dd2be2bb8a61ee8da16e0f0/.github/workflows/configlet.yml#L19

---

At the time of writing, the list of track files that contain `configlet-ci` is:
```
bash/.github/workflows/configlet.yml
clojurescript/.github/workflows/configlet.yml
delphi/.github/workflows/configlet.yml
elixir/.github/workflows/configlet.yml
elm/.github/workflows/configlet.yml
fortran/.github/workflows/configlet.yml
gleam/.github/workflows/configlet.yml
go/.github/workflows/configlet.yml
javascript/.github/workflows/configlet.yml
julia/.github/workflows/configlet.yml
nim/.github/workflows/configlet.yml
perl5/.github/workflows/configlet.yml
pharo-smalltalk/.github/workflows/ci.yml
php/.github/workflows/configlet.yml
python/.github/workflows/ci-workflow.yml
r/.github/workflows/configlet.yml
raku/.github/workflows/configlet.yml
ruby/.github/workflows/configlet.yml
scheme/.github/workflows/configlet.yml
shen/.github/workflows/configlet.yml
tcl/.github/workflows/configlet.yml
typescript/.github/workflows/configlet.yml
vbnet/.github/workflows/configlet.yml
x86-64-assembly/.github/workflows/configlet.yml
```

Note that not every file is named `configlet.yml`. To be precise: the `v3-migration` branch adds a `configlet.yml` to pharo-smalltalk and python, but those tracks already contain `ci.yml` and `ci-workflow.yml` respectively - each already uses the `configlet-ci` action.

**Comment by ee7** [comment]
@SaschaMann Do you know if workflows that use `exercism/github-actions/configlet-ci@master` will continue to work if we rename the default branch in this repo from `master` to `main`? Or would we need to temporarily have both a `master` and a `main` branch in this repo if we can't fix the above issue in time?

And is there any other Exercism repo that could perhaps benefit from temporarily having both branches?

Also pinging @iHiD.

**Comment by iHiD** [comment]
> And is there any other Exercism repo that could perhaps benefit from temporarily having both branches?

I think this is a bad idea. It means people will end up accidently pulling/rebasing from master (I've tried to do this lots of times and only the lack of that branch has stopped me). 

@ErikSchierboom This is probably a good one for you to add to the migration script tomorrow morning before we run it. Basically anything of the pattern `exercism/*@master` should change to `exercism/*@master` I guess?

**Comment by iHiD** [comment]
(It worth noting that `exercism/configlet` will be what is currently `canonical-data-syncer` when we do this tomorrow)

**Comment by SaschaMann** [comment]
> Do you know if workflows that use exercism/github-actions/configlet-ci@master will continue to work if we rename the default branch in this repo from master to main? 

I have no idea. We'll find out I guess.

> I think this is a bad idea. It means people will end up accidently pulling/rebasing from master (I've tried to do this lots of times and only the lack of that branch has stopped me).

I think for this particular repo, that's not a big issue because there's barely any contributors to it.

**Comment by ErikSchierboom** [comment]
> This is probably a good one for you to add to the migration script tomorrow morning before we run it. Basically anything of the pattern exercism/*@master should change to exercism/*@main I guess?

@SaschaMann @iHiD I've added this to my migration script.

**Comment by ErikSchierboom** [comment]
As of today, the default branch of this repository has been changed to main.
