### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by wolf99** [exercism/github-actions#29]
I noticed that the Exercism actions used in C track are not pinned to a version, but instead use `@main`. This seems to be because this repo does not have releases.

Perhaps this is intentional so that all repos that use these actions will always be up to date without needing to depend on dependabot (slight pun intended) ?

If not then it may be good to be able to pin to SHAs of releases.
Then, unless happy to always release all actions at the same time every time, I believe that implies that multiple actions should not be housed in the same repository. Thus meaning that this repo should split to at least 2 repos given the current contents.

Is there some other overriding reason(s) that the actions are housed in a single repo?

**Comment by SaschaMann** [comment]
> Also discussed was how repo permissions might affect this with regard to using @main. The concensus was that as long as merge rights are kept to those with reviewer rights it should be OK.

I wonder if branches or tag names take precedence if you push a tag called `main`. There's no way to protect against tag pushes, I think.

**Comment by SaschaMann** [comment]
It seems like branches take precedence, see the logs of the PR above:

```
Download action repository 'actions/checkout@v2.3.4' (SHA:5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f)
Download action repository 'SaschaMann/github-actions@main' (SHA:b7e7c90fdf09ea966820210c3560b9d58f5c86d6)
```

`b7e7c90fdf09ea966820210c3560b9d58f5c86d6` corresponds to the latest commit on main.

So branch protections would be sufficient.

**Comment by wolf99** [comment]
How does one use the bulk change? 
Or is that maintainers admin only?

**Comment by SaschaMann** [comment]
> How does one use the bulk change?
> Or is that maintainers admin only?

Everyone can do it. @ErikSchierboom probably has some scripts for it but otherwise it involves some shell scripting and the github cli generally. The configlet workflow is not (yet?) synced via org-wide-files.

**Comment by ErikSchierboom** [comment]
> The configlet workflow is not (yet?) synced via org-wide-files.

I think we _do_ want this, as it should be the same for all tracks.

**Comment by SaschaMann** [comment]
In that case, you could open a PR that adds the workflow to https://github.com/exercism/org-wide-files/tree/main/tracks-files, @wolf99

**Comment by wolf99** [comment]
> In that case, you could open a PR that adds the workflow to https://github.com/exercism/org-wide-files/tree/main/tracks-files,

Looks like this will be covered by https://github.com/exercism/org-wide-files/pull/10, if  https://github.com/exercism/configlet/pull/462 gets merged beforehand.

**Comment by SaschaMann** [comment]
This has been superseded by the change to reusable and synced configlet workflows, I think. But feel free to reopen if I'm wrong.
